#!/usr/bin/env php
<?php
use OxidEsales\Eshop\Core\Registry;

$bootstrapFileName = realpath(trim(getenv('ESHOP_BOOTSTRAP_PATH')));

if (!(file_exists($bootstrapFileName) && !is_dir($bootstrapFileName))) {
    $items = [
        "Unable to find eShop bootstrap.php file.",
        "You can override the path by using ESHOP_BOOTSTRAP_PATH environment variable.",
        "\n"
    ];

    $message = implode(" ", $items);

    die($message);
}

require_once($bootstrapFileName);

$config = Registry::get('oxConfigFile');
$config->setVar('aSlaveHosts', null);

$metaDataHandler = oxNew('oxDbMetaDataHandler');

$status = (object)[
    'updateViews' => false,
    'noException' => false
];

function handleExit($status) {
    if ((!$status->updateViews) || (!$status->noException)) {
        print("There was an error while regenerating the views.");
    }

    if (!$status->noException) {
        print(" Please look at `EXCEPTION_LOG.txt` for more details.\n");
    }

    if (($status->noException) && (!$status->updateViews)) {
        print(" Please double check the state of database and configuration.\n");
    }
}

register_shutdown_function('handleExit', $status);

$status->updateViews = $metaDataHandler->updateViews();
$status->noException = true;

if (!$status->updateViews) {
    exit(2);
}
