#!/usr/bin/env php
<?php
use OxidEsales\Eshop\Core\Registry;

$bootstrapFileName = realpath(trim(getenv('ESHOP_BOOTSTRAP_PATH')));

if (!(file_exists($bootstrapFileName) && !is_dir($bootstrapFileName))) {
    $items = [
        "Unable to find eShop bootstrap.php file.",
        "You can override the path by using ESHOP_BOOTSTRAP_PATH environment variable.",
        "\n"
    ];

    $message = implode(" ", $items);

    die($message);
}

require_once($bootstrapFileName);

$config = Registry::get('oxConfigFile');
$config->setVar('aSlaveHosts', null);

$metaDataHandler = oxNew('oxDbMetaDataHandler');

if ($metaDataHandler->updateViews()) {
  echo 1;
} else {
  echo 0;
}